HERE.make "Rick's Cabaret", crossstreets: ['15th', 'Stout'], types: ['bar', 'club'], areas: ['midtown', 'updn']
HERE.make "Diamond Cabaret", crossstreets: ['13th', 'Glenarm'], types: ['bar', 'club'], areas: ['colfax', 'updn'] 
HERE.make "Meadowlark", crossstreets: ['27th', 'Larimer'], types: ['bar', 'venue'], areas: ['rhino', 'larimer']
HERE.make "Scruffy Murphy's", crossstreets: ['20th', 'Larimer'], types: ['bar', 'venue'], areas: ['lodo']
HERE.make "Beer Hall", crossstreets: ['20th', 'Larimer'], types: ['bar'], areas: ['lodo']
HERE.make "Retro Room", crossstreets: ['20th', 'Larimer'], types: ['bar'], areas: ['lodo']
HERE.make "Zanzibar", crossstreets: ['21st', 'Larimer'], types: ['bar', 'food'], ammenities: ['pool', 'darts'], areas: ['lodo']
HERE.make "Brother's Market", crossstreets: ['21st', 'Larimer'], types: ['store'], areas: ['lodo']
HERE.make "Black Bar", crossstreets: ['21st', 'Larimer'], types: ['bar'], areas: ['lodo']
HERE.make "Gin Mill", crossstreets: ['21st', 'Larimer'], types: ['bar'], areas: ['lodo']
HERE.make "Born", crossstreets: ['16th', 'Wewatta'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['union station']
HERE.make "Hyatt Regency", crossstreets: ['15th', 'California'], types: ['hotel'], areas: ['updn', 'midtown']
HERE.make "La Meridian", crossstreets: ['15th', 'California'], types: ['hotel', 'bar'], areas: ['updn', 'midtown']
HERE.make "AC Marriot", crossstreets: ['15th', 'California'], types: ['hotel', 'bar'], areas: ['updn', 'midtown']
HERE.make "Embassy Suites", crossstreets: ['14th', 'Stout'], types: ['hotel'], areas: ['updn', 'midtown']
HERE.make "Thompson", crossstreets: ['16th', 'Market'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['lodo', 'union station']
HERE.make "Rally", crossstreets: ['19th', 'Wynkoop'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['lodo', 'union station', 'ballpark']
HERE.make "Maven", crossstreets: ['19th', 'Wazee'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['lodo', 'ballpark']
HERE.make "Crawford", crossstreets: ['17th', 'Wynkoop'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['union station']
HERE.make "Oxford", crossstreets: ['17th', 'Wynkoop'], types: ['hotel', 'valet', 'consierge'], areas: ['union station']
HERE.make "Brown Palace", crossstreets: ['17th', 'Tremont'], types: ['hotel', 'bar', 'valet', 'consierge'], areas: ['updn', 'broadway']
HERE.make "Holiday Inn", crossstreets: ['17th', 'Tremont'], types: ['hotel'], areas: ['updn']
HERE.make "Grand Hyatt", crossstreets: ['17th', 'Welton'], types: ['hotel', 'valet', 'consierge'], areas: ['updn']
HERE.make "Monaco", crossstreets: ['17th', 'Champa'], types: ['hotel', 'valet', 'consierge'], areas: ['updn', 'midtown']
HERE.make "Renaissance", crossstreets: ['16th', 'Champa'], types: ['hotel', 'valet', 'bar', 'consierge'], areas: ['midtown']
HERE.make "Magnolia", crossstreets: ['17th', 'Stout'], types: ['hotel', 'consierge'], areas: ['midtown']
HERE.make "Hyatt Centric", crossstreets: ['18th', 'Champa'], types: ['hotel', 'consierge'], areas: ['midtown']
HERE.make "Ramble", crossstreets: ['24th', 'Larimer'], types: ['hotel', 'bar', 'consierge'], areas: ['rhino', 'larimer']
HERE.make "Indego", crossstreets: ['18th', 'Wewatta'], types: ['hotel', 'bar'], areas: ['union station']
HERE.make "Hilton Garden Inn Union Station", crossstreets: ['20th', 'Chestnut'], types: ['hotel'], areas: ['union station']
HERE.make "Hilton Garden Inn Updn", crossstreets: ['15th', 'Welton'], types: ['hotel'], areas: ['updn']
HERE.make "Hampton Inn & Suites", crossstreets: ['15th', 'Welton'], types: ['hotel'], areas: ['updn']
HERE.make "Spring Hill Suites", crossstreets: ['Speer', 'Araria'], types: ['hotel', 'valet'], areas: ['arena']
HERE.make "Residence Inn", crossstreets: ['18th', 'Champa'], types: ['hotel'], areas: ['midtown']
HERE.make "Hyatt Place", crossstreets: ['14th', 'Glenarm'], types: ['hotel'], areas: ['updn', 'colfax']
HERE.make "Hyatt House", crossstreets: ['14th', 'Glenarm'], types: ['hotel'], areas: ['updn', 'colfax']
HERE.make "Front Porch", crossstreets: ['15th', 'Lawrence'], types: ['bar'], areas: ['larimer square']
HERE.make "Rosevelt", crossstreets: ['15th', 'Lawrence'], types: ['bar'], areas: ['larimer square']
HERE.make "Ocean Prime", crossstreets: ['15th', 'Larimer'], types: ['bar', 'food'], areas: ['larimer square']
HERE.make "Capitol Grill", crossstreets: ['15th', 'Larimer'], types: ['bar', 'food'], areas: ['larimer square']
HERE.make "Disco Pig", crossstreets: ['14th', 'Larimer'], types: ['bar'], areas: ['larimer square']
HERE.make "Tomayo", crossstreets: ['14th', 'Larimer'], types: ['bar', 'food'], areas: ['larimer square']
HERE.make "Wally's", crossstreets: ['14th', 'Market'], types: ['bar', 'food'], areas: ['lodo', 'river']
HERE.make "Celtic", crossstreets: ['14th', 'Market'], types: ['bar', 'food'], areas: ['lodo', 'river']
HERE.make "Pour House", crossstreets: ['14th', 'Market'], types: ['bar', 'food'], areas: ['lodo', 'river']
HERE.make "Nallen's", crossstreets: ['14th', 'Market'], types: ['bar', 'food'], areas: ['lodo', 'river']
HERE.make "Nola Jane", crossstreets: ['15th', 'Market'], types: ['bar', 'food'], areas: ['lodo', 'river']
HERE.make "Gas Lamp", crossstreets: ['15th', 'Market'], types: ['bar'], areas: ['lodo', 'river']
HERE.make "Society", crossstreets: ['14th', 'Blake'], types: ['bar'], areas: ['lodo', 'river']
HERE.make "Hayters", crossstreets: ['19th', 'Blake'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "Tap XIV", crossstreets: ['19th', 'Blake'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "Sports Column", crossstreets: ['20th', 'Blake'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "1up", crossstreets: ['20th', 'Blake'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "Swanky's", crossstreets: ['20th', 'Blake'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "Giggling Grizley", crossstreets: ['20th', 'Market'], types: ['bar'], areas: ['lodo', 'ballpark']
HERE.make "El Tejon", crossstreets: ['20th', 'Market'], types: ['bar'], areas: ['lodo']
HERE.make "STATUS", crossstreets: ['18th', 'Blake'], types: ['bar'], areas: ['midtown']
HERE.make "Rio", crossstreets: ['19th', 'Wazee'], types: ['food' 'bar'], areas: ['midtown', 'ballpark']
